-- Run this in the Supabase SQL Editor to add the collab task-board table.
-- (Matches collab/migrations/0006_collabtask.py.) Safe to run once.

BEGIN;

CREATE TABLE "collab_collabtask" (
    "id"           bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title"        varchar(200) NOT NULL,
    "is_done"      boolean NOT NULL,
    "created_at"   timestamp with time zone NOT NULL,
    "assignee_id"  bigint NULL,
    "collab_post_id" bigint NOT NULL,
    "created_by_id"  bigint NOT NULL
);

ALTER TABLE "collab_collabtask"
    ADD CONSTRAINT "collab_collabtask_assignee_id_fk_users_user"
    FOREIGN KEY ("assignee_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "collab_collabtask"
    ADD CONSTRAINT "collab_collabtask_collab_post_id_fk_collab_collabpost"
    FOREIGN KEY ("collab_post_id") REFERENCES "collab_collabpost" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "collab_collabtask"
    ADD CONSTRAINT "collab_collabtask_created_by_id_fk_users_user"
    FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "collab_collabtask_assignee_id_idx" ON "collab_collabtask" ("assignee_id");
CREATE INDEX "collab_collabtask_collab_post_id_idx" ON "collab_collabtask" ("collab_post_id");
CREATE INDEX "collab_collabtask_created_by_id_idx" ON "collab_collabtask" ("created_by_id");

COMMIT;
