-- Run this in the Supabase SQL Editor to add read receipts + typing indicator
-- support. (Matches work/migrations/0008_message_read_at_typingstatus.py.)
-- Safe to run once.

BEGIN;

ALTER TABLE "work_message" ADD COLUMN "read_at" timestamp with time zone NULL;

CREATE TABLE "work_typingstatus" (
    "id"              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "updated_at"      timestamp with time zone NOT NULL,
    "conversation_id" bigint NOT NULL,
    "user_id"         bigint NOT NULL
);

ALTER TABLE "work_typingstatus"
    ADD CONSTRAINT "work_typingstatus_conversation_id_fk_work_conversation"
    FOREIGN KEY ("conversation_id") REFERENCES "work_conversation" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "work_typingstatus"
    ADD CONSTRAINT "work_typingstatus_user_id_fk_users_user"
    FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "work_typingstatus"
    ADD CONSTRAINT "work_typingstatus_conversation_id_user_id_uniq"
    UNIQUE ("conversation_id", "user_id");

CREATE INDEX "work_typingstatus_conversation_id_idx" ON "work_typingstatus" ("conversation_id");
CREATE INDEX "work_typingstatus_user_id_idx" ON "work_typingstatus" ("user_id");

COMMIT;
