# Generated by Django 6.0.3 on 2026-03-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collabrequest",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collabrequest",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
