# Generated by Django 6.0.3 on 2026-08-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0010_hot_path_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="media_type",
            field=models.CharField(
                blank=True,
                choices=[("image", "Image"), ("video", "Video")],
                default="",
                max_length=10,
            ),
        ),
    ]
