# Generated by Django 6.0.3 on 2026-03-22 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="description",
            field=models.CharField(
                help_text="Max 200 characters — keep it short and to the point",
                max_length=200,
                validators=[django.core.validators.MaxLengthValidator(200)],
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
