# Generated by Django 6.0.3 on 2026-03-22 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_portfolioitem_latitude_portfolioitem_longitude_and_more"),
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="verified_via_work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portfolio_items",
                to="work.workrequest",
            ),
        ),
    ]
