# Generated by Django 6.0.3 on 2026-08-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_portfolioitem_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioitem",
            name="portfolio_type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("design", "Design"),
                    ("photo", "Photo"),
                    ("baked_good", "Baked Good"),
                    ("artwork", "Artwork"),
                    ("video", "Video"),
                    ("status", "Status"),
                    ("other", "Other"),
                ],
                default="project",
                max_length=20,
            ),
        ),
    ]
