# Generated by Django 6.0.3 on 2026-09-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_hot_path_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("work_request", "Work Request"),
                    ("proposal", "Proposal"),
                    ("proposal_accepted", "Proposal Accepted"),
                    ("proposal_declined", "Proposal Declined"),
                    ("work_assigned", "Work Assigned"),
                    ("message", "Message"),
                    ("reaction", "Reaction"),
                    ("comment", "Comment"),
                    ("referral", "Referral"),
                    ("job_complete", "Job Complete"),
                    ("job_review", "Job Review"),
                    ("job_confirm", "Job Confirm"),
                    ("friend_request", "Friend Request"),
                    ("friend_accepted", "Friend Accepted"),
                    ("collab_match", "Collab Match"),
                ],
                max_length=20,
            ),
        ),
    ]
