-- Run this in the Supabase SQL Editor to add the friends feature.
-- (Matches users/migrations/0012_friendship.py.) Safe to run once.
-- The notification-type change needs NO SQL — choices are enforced in Django only.

BEGIN;

CREATE TABLE "users_friendship" (
    "id"           bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "status"       varchar(10) NOT NULL,
    "created_at"   timestamp with time zone NOT NULL,
    "receiver_id"  bigint NOT NULL,
    "requester_id" bigint NOT NULL
);

ALTER TABLE "users_friendship"
    ADD CONSTRAINT "users_friendship_requester_receiver_uniq"
    UNIQUE ("requester_id", "receiver_id");

ALTER TABLE "users_friendship"
    ADD CONSTRAINT "users_friendship_receiver_id_fk_users_user"
    FOREIGN KEY ("receiver_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "users_friendship"
    ADD CONSTRAINT "users_friendship_requester_id_fk_users_user"
    FOREIGN KEY ("requester_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "users_friendship_receiver_id_idx"  ON "users_friendship" ("receiver_id");
CREATE INDEX "users_friendship_requester_id_idx" ON "users_friendship" ("requester_id");

COMMIT;
