-- Run this in the Supabase SQL Editor to create the push-subscription table.
-- (Matches users/migrations/0010_pushsubscription.py.) Safe to run once.
-- Needed for browser push notifications (messages, proposal accepted, etc.)
-- to actually reach a signed-out/backgrounded user's device.

BEGIN;

CREATE TABLE "users_pushsubscription" (
    "id"         bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "endpoint"   text NOT NULL UNIQUE,
    "p256dh"     varchar(255) NOT NULL,
    "auth"       varchar(255) NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "user_id"    bigint NOT NULL
);

ALTER TABLE "users_pushsubscription"
    ADD CONSTRAINT "users_pushsubscription_user_id_fk_users_user"
    FOREIGN KEY ("user_id") REFERENCES "users_user" ("id")
    DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "users_pushsubscription_user_id_idx"
    ON "users_pushsubscription" ("user_id");

COMMIT;
